### PR TITLE
Select the contents of the request info content area when CTRL+A is pressed

### PR DESCRIPTION
**Pull request by khlr**
This pull request refers to issue #28.
So far <kbd>CTRL</kbd>+<kbd>A</kbd> selected the contents of the trace window. To copy a traced request in this way was very cumbersome because the relevant part had to be manually selected.

This key binding is now overridden to just select the contents of the request info content area. I think that's a convenient solution and avoids the need for another button in the UI.

--

With commit 8d10bce the selection is sustained even if the user switches form e.g. the HTTP-tab to the Parameters-tab. At first this felt a bit odd to me because I wouldn't expect the selection to be kept sustained. But then I thought that this could be quite handy. Nevertheless, the selection is removed when another request gets clicked.

What to do you think?

peek 2018-01-22 21-10

### CODE REVIEW

**Comment by thijskh** [comment]
Works very nicely!

**Comment by jaimeperez** [comment]
This looks very useful indeed! But again, we have conflicts 😞

**Comment by khlr** [comment]
It's fixed an ready :)

**Comment by jaimeperez** [comment]
... aaaaand merged too! 😄 

Thanks a lot again @khlr!

**Pull request merged**
