### PR TITLE
Consider svg images and (web)fonts to be resources.

### PR DESCRIPTION
**Pull request by thijskh**
The 'filter resources' option now also filters svg images and webfonts.

### CODE REVIEW

**Comment by khlr** [comment]
Nice, Thijs! These requests can be really annoying.
Could you additionally add `application/font-woff`? I noticed this type, too.

Moreover there can be often a bunch of `application/json`-requests that bloat the trace window. But I think this type may be a bit critically since these requests could be a (desired) response of an web API or something like that. What do you think?

**Comment by thijskh** [comment]
Added `application/font-woff`. I think filtering out json is out of scope at least for this option, that tries to filter out things that we are 'sure' to be irrelevant.

**Comment by khlr** [comment]
Agreed!

**Comment by khlr** [comment]
Just one other small thing:
Please additionally add `application/font-woff2`.

**Comment by tvdijen** [comment]
Except from `application/json`, would there be any other `application/xxx` types that need to pass??
If not, I think we can safely reduce the amount of cases by excluding `application/*` and 'image/*'

**Comment by khlr** [comment]
I agree that it's very likely that there are more ex- than includes, Tim.
But I think Thijs mentioned a very important point: If it's not really certain that a request can be discarded it'd be _safer_ to have it included. 

I could very well imagine that'd be fairly annoying if relevant requests would be filtered away due to an `application/*` content-type.

On the other hand it'd be hard to safely predict all relevant content-types.
Hence I think it'd be a good idea stick with the current exclude-approach and exclude only those request that are safe to exclude.

**Comment by tvdijen** [comment]
In that case, we should exclude audio/*. video/* www/* and message/* ...
IMHO, it's not the end of the world if something legit gets excluded... We can always show it with the button.

**Comment by thijskh** [comment]
I've added `application/font-woff`.

@tvdijen My approach to this issue is quite pragmatic:
- The code already works with a switch/case statement, so adding some more types is a simple change and does not require additional code changes;
- I don't see that many video/* stuff polluting my SAML traces in practice (as in: I never see that).
So this simple change makes it work just fine for me.
I'm leaving my PR at this for now.

**Pull request merged**
