### PR TITLE
Feature/gh 25 export function

### PR DESCRIPTION
**Pull request by khlr**
This is the pull request for issue #25, bringing back the export and import functionality.
As with the last PRs: I'd be glad if someone could do a review :-)

### CODE REVIEW

**Comment by thijskh** [comment]
Great! I did two initial tests with two completely different SAML flows, and both export fine but the import of the just exported file in both cases yields "Error while importing: InvalidCharacterError: String contains an invalid character".

I can email you the output if that's useful.

I can look into more detail later.

**Comment by khlr** [comment]
Yep, it'd be very interesting to have a look at your exports!
I've tested on both Windows and Linux but didn't experience this result.

**Comment by khlr** [comment]
I didn't take into account that SAMLResponses may not be re-constructible if the POST-array was obfuscated or removed during the preceding export.

Thanks for the samples, @thijskh. And thank you very much (!) for the moo-archive test-account, @tvdijen! It really helped me a lot with this 👍

**Comment by thijskh** [comment]
Good, im-/export works robustly now!

**Pull request merged**
