### PR TITLE
Used highlight.js to add syntax highlighting to the content area.

### PR DESCRIPTION
**Pull request by khlr**
Hello everyone!

I thought some syntax highlighting would by quite useful. Hence I used Highlight.js to colorize the content details:

image

Do you all agree to add this functionality? Should there be a button to switch the highlighting on or off (just asking, in case...)?

### CODE REVIEW

**Comment by tvdijen** [comment]
This is great stuff!
Personally I don't think this needs a switch as long as we keep it readable for people that are color blind... Might reconsider the color-scheme.

**Comment by thijskh** [comment]
Yes, very useful. Perhaps best to use the color scheme that Firefox uses for view-source?

**Comment by khlr** [comment]
I've been very focused on the Firefox color scheme. It nearly completely matches it.
@tvdijen, which color scheme would be more appropriate?

**Comment by tvdijen** [comment]
You could fiddle around with the above image and this website:
http://www.color-blindness.com/coblis-color-blindness-simulator/

Epecially if you select Red-blind or Green-blind, everything becomes pretty much one color and thus hard to read.
Would it be an idea to keep te current color-scheme by default and be able to switch to an alternative scheme?

**Comment by tvdijen** [comment]
Aye!

**Comment by khlr** [comment]
If all agree, I think this PR should be ready for a merge 😃
@thijskh, would you be so kind and do a review again?

**Comment by jaimeperez** [comment]
Thanks a lot for this @khlr!

Since getting back the import/export functionality was more important than a cosmetic enhancement like this, I merged that PR first. Unfortunately, that means now that we have conflicts in this PR so it can't be automatically merged. Do you mind taking a look at it and fixing the conflicts so that I can merge it?

**Comment by jaimeperez** [comment]
Wonderful! Thanks again for your hard work @khlr!

**Pull request merged**
