### PR TITLE
The function `xmlEntities` should be removed

### PR DESCRIPTION
**Pull request by khlr**
This PR fixes the issues mentioned in #26 and #52.

### CODE REVIEW

**Comment by khlr** [comment]
What about merging this PR as well, @jaimeperez? 
Could form a nice bugfix release (e.g. 1.5.2?) :-)

**Comment by jaimeperez** [comment]
Hi @khlr!

Does this keep values structured as XML? I'm thinking particularly about the case where we have a NameID as an attribute's value that I was mentioning [here](https://github.com/Uninett/SAML-tracer/issues/52#issuecomment-494759045).

**Comment by khlr** [comment]
Maybe we better resume the conversation at issue #52 to not have the discussion at two places, @jaimeperez 🙂

**Comment by jaimeperez** [comment]
Hi @khlr!

I understand there are no pending issues here and we could merge this, right?

**Comment by khlr** [comment]
Exactly :-)

**Pull request merged**
